### ISSUE TITLE
🗺 Wump's Assistance Roadmap

### ISSUE THREAD

**Issue by Nziie3** [Nziie3/wumpus-assistance#12]
# Roadmap - Wump's Assistance
  - **This is a roadmap for Wump's Assistance**
  - **All future plans for the bot will be categorized in a list with check boxes**
  - `If the checkbox IS checked, that means it is complete and implemented as a feature in the bot`
  - `If the checkbox IS NOT checked, that means it is not completed and/or planned`
---
- [ ] Blacklist role configuration
  - [ ] Won't allow user's in that role to open tickets
- [ ] Variables for the ticket embed
  - e.g. `$USER.NAME` = the ticket author's name etc
